version: '3'
services:
  docker-mysql:
    image: mysql:5.7.6
    environment:
      MYSQL_ROOT_PASSWORD: abullrich
      MYSQL_DATABASE: abullrichdb
      MYSQL_USER: root
      MYSQL_PASSWORD: abullrich
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=abullrich --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - 5306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: docker-mysql

  generic-crud-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 6080:8080
    environment:
      - MYSQL_SERVER=docker-mysql
    depends_on:
      - docker-mysql

volumes:
  mysql-data: